const places = [
  {
    _id: "65d7b289bd1e430a108f0a7d",
    name: "Lakshadweep",
    state: "Union Territory",
    city: "Lakshadweep",
    info: "Formerly known as Laccadive Islands, Lakshadweep translates to 'one hundred thousand islands' in Malayalam. Home to a few of the most beautiful and exotic islands and beaches of India,\n Lakshadweep lies 400km off the southwest coast of the Arabian Sea. The smallest union territory of India has only 36 islands having a total area of 32 sq. kilometres. It's made up of 12 atolls, 3 reefs and 5 submerged banks out of which ten Islands are inhabited. \n Lakshadweep is typically accessed from Kochi (Kerala) and a permit is required to visit Lakshadweep for all tourists (including Indians). After permit, foreigners are permitted to just visit Agatti, Bangaram and Kadmat Islands. Permits can be obtained from Kochi itself. Permits are exempted to government officials, armed force members, and their families who are either working or visiting these islands. Additionally, embarking on the Lakshadweep Samudram Cruise aboard MV Kavaratti is a maritime adventure like no other. This 5 day cruise takes you Kavaratti, Minicoy and Kalpeni islands. Another such extraordinary 5-day voyage is from Mumbai to Lakshadweep on the Cordelia Cruise.\n Perhaps the charm of Lakshadweep islands lies in their remoteness. Far off the beaten track, they attract no hordes of merrymakers to their shores. The islands, though all equally mystical and beautiful, each offers a unique blend of tourist spots. Some islands have been promoted for diving and water sports, still, others have been developed so that people enjoy the charm of relaxation.",
    weather: "27 - 28°C",
    best_time_of_visit: "September to Feruary",
    image: "https://www.holidify.com/images/bgImages/LAKSHADWEEP.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b2f4bd1e430a108f0a81",
    name: "Taj Mahal",
    state: "Uttar Pradesh",
    city: "Agra",
    info: "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. \n It was commissioned in 1632 by the Mughal emperor, Shah Jahan, to house the tomb of his favourite wife, Mumtaz Mahal.The tomb is the centrepiece of a 17-hectare complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall. Construction of the mausoleum was essentially completed in 1643 but work continued on other phases of the project for another 10 years. \n The Taj Mahal complex is believed to have been completed in its entirety in 1653 at a cost estimated at the time to be around 32 million rupees, which in 2015 would be approximately 52.8 billion rupees.The construction project employed some 20, 000 artisans under the guidance of a board of architects led by the court architect to the emperor, Ustad Ahmad Lahauri.\nThe Taj Mahal was designated as a UNESCO World Heritage Site in 1983 for being the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage. It is regarded by many as the best example of Mughal architecture and a symbol of India's rich history.",
    weather: "Summers (April to June),Winters (October to March)",
    best_time_of_visit: "October to March",
    image: "https://www.tajmahal.gov.in/images/tajmahal-view/day/1.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b337bd1e430a108f0a83",
    name: "Jaipur",
    state: "Rajasthan",
    city: "Jaipur",
    info: "Jaipur, the capital city of Rajasthan, stands as a jewel in the crown of the Golden Triangle, alongside Delhi and Agra. \n This enchanting city, often referred to as the Pink City, owes its nickname to the terracotta-pink hue that adorns many of its buildings.\n  The Pink City is a testament to the royal heritage of Rajasthan, known for its magnificent palaces, vibrant bazaars, and imposing forts. One of the largest cities in India, Jaipur is also home to all the modern amenities with some of the most exotic hotels and resorts in the world. The city boasts an international airport and is also very well connected by rail and road. This makes Jaipur the gateway to Rajasthan - the starting point for places to visit in the interiors of the state. The city is a treasure trove of must-visit attractions, with the Hawa Mahal (Palace of Winds) standing as an iconic symbol of Jaipur's architectural prowess. The Amber Fort, another jewel in Jaipur's crown, showcases the grandeur of Rajput architecture.  Jaipur is home to UNESCO World Heritage Sites, including the Jantar Mantar and the City Palace. Exploring Jaipur is incomplete without a stroll through its bustling markets. The Johari Bazaar and Bapu Bazaar are famous for their traditional Rajasthani jewelry, textiles, and handicrafts. The city is also very well known for its local cuisine, and the most famous dishes include the Ghewar, Pyaaz Kachori and Dal Baati Churma. The city also hosts the Jaipur Literary Festival, which is Asia's biggest festival of its kind. The city's vibrant culture comes alive during festivals like Diwali and Holi, with lively processions, cultural performances, and colorful celebrations. Rajputs ruled Jaipur for many centuries and developed as a planned city in the 17th century AD. With the old city surrounded by walls and gates decorated with drawings on the backdrop of a beautiful pink hue, Jaipur, the pink city, successfully retains its old-world charm.",
    weather: "Hot summers, pleasant winters (October to March)",
    best_time_of_visit: "October to March",
    image: "https://www.holidify.com/images/bgImages/JAIPUR.jpg",
    reviews: [
      {
        _id: "65d7c76166bbee4f8e71ce4b",
        author: {
          _id: "65d7c1e9bd1e430a108f0abb",
          firstName: "Gautam",
          lastName: "Sharma",
        },
        comment: "Good Place! Must Visit",
        timeAdded: "2024-02-22T22:14:57.335Z",
        __v: 0,
      },
      {
        _id: "65d7c7afc5a79193f807ac6e",
        author: {
          _id: "65d7c1e9bd1e430a108f0abb",
          firstName: "Gautam",
          lastName: "Sharma",
        },
        comment: "Good Place! Must Visit",
        timeAdded: "2024-02-22T22:16:15.359Z",
        __v: 0,
      },
    ],
    __v: 2,
  },
  {
    _id: "65d7b344bd1e430a108f0a85",
    name: "Goa",
    state: "Goa",
    city: "Panaji",
    info: "Lying on the western coast, Goa is India's smallest state and unlike any other, known for its endless beaches, \n stellar nightlife, eclectic seafood, world-heritage listed architecture. Spread across just 3,702 km, Goa lies in the Konkan region. It is a far cry from the hippie haven or a beach getaway, and one of the only few destinations that is open 24x7. The laid-backness (susegad) of Goa attracts as many international tourists as it does Indians, or even more so. \n The Goans are quite friendly towards tourists and celebrate many festivals throughout the year, the most famous being the New Year and Goa Carnival. While the seafood is excellent, Goa has one of the best nightlife in India with trendy bars, beach shacks, elegant cafes and many clubs and discotheques. Thanks to lower alcohol prices in the state, Goa is also great for younger tourists with relatively tighter pockets.\n  For those of us perpetually confused between North Goa and South Goa, this might help - the state of Goa is divided into North Goa and South Goa. While North Goa is the nightlife hub where all the touristy beaches, flea markets, and beach shacks are located, South Goa is the land of luxurious resorts and laid-back beach vibes. \n Having been a Portuguese territory for almost 450 years, the Portuguese architecture is nowhere as prevalent as in Goa - visit one of the many whitewashed churches, crumbling forts or spectacular churches. The yellow houses with purple doors, ochre coloured mansions and oyester shell windows is what completes the kalieodscope of Goan architecture.\n Panjim, the capital city located in the centre overlooks the calm Mandovi River where the famous floating casinos of Goa are docked. The centre is well-connected with an international airport and roads and trains run from North to South part of Goa. With a coastline stretching for over 100 kilometres, Goa has stunning beaches. While Baga and Calangute are more popular among the Indian family crowd, Anjuna and Arambol draw a lot of foreign tourists. The beaches in South Goa are relatively lesser explored, but some of them like Agonda and Palolem are more beautiful.",
    weather: "Hot and humid (April to September), moderate (October to March)",
    best_time_of_visit: "November to February",
    image: "https://www.holidify.com/images/bgImages/GOA.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b352bd1e430a108f0a87",
    name: "Kerala",
    state: "Kerala",
    city: "Various",
    info: "Nestled in the southwestern corner of India, Kerala, often referred to as Gods Own Country, is a land of enchanting beauty and rich cultural \n tapestry. Lush with tropical vegetation, pristine beaches, serene backwaters and a variety of flora and fauna, Kerala is an ideal destination for honeymooners and families.\n  The famous backwaters of Alleppey and Kumarakom, adorned with houseboats gently gliding on tranquil waters, epitomize the unique charm of Kerala.\n Kerala is divided into three distinct regions  – Malabar, Cochin, and Travancore – comprising a total of 14 districts each offering a unique experience. The Malabar region, with its historic spice trade, has a rich cultural heritage. Kochi, a bustling port city, reflects the influence of various colonial powers through its architecture and cuisine. The southern region of Travancore boasts majestic temples and pristine beaches, contributing to the states diverse charm. \n Kerala also boasts thriving wildlife sanctuaries and lush tea plantations. The Periyar Wildlife Sanctuary, nestled in the Western Ghats, offers a haven for diverse flora and fauna.  The idyllic hill station of Munnar is renowned for its vast tea plantations, where emerald-green slopes carpet the landscape. Keralas cuisine is a gastronomic delight, featuring a variety of flavorful dishes. The traditional meal, known as Sadya, served on a banana leaf, showcases an array of curries, rice, and accompaniments. The state is renowned for its spices, and the cuisine reflects a perfect blend of aromatic herbs and distinctive flavors. \n The culture of Kerala is deeply rooted in its traditions and arts. The state celebrates Onam, a harvest festival of Kerala, with grandeur, marked by elaborate feasts, traditional games, and vibrant cultural performances. Thrissur Pooram, another major festival, is a spectacular display of colors, music, and fireworks. Kathakali, a classical dance form, and Theyyam, a ritualistic performance art, showcase the states rich cultural heritage. The traditional martial art form of Kalaripayattu, believed to be one of the oldest in the world, adds another layer to Keralas cultural landscape.\n Keralas international airports, including Trivandrum, Cochin, and Calicut, facilitate seamless connectivity, welcoming visitors from around the globe. The state is a haven for Ayurveda, with rejuvenating practices deeply ingrained in its culture. Ayurvedic resorts and wellness centers, nestled amidst serene landscapes, offer holistic experiences, blending traditional therapies, herbal treatments, and yoga. The best time to visit Kerala is during the winter months, from October to March, when the weather is pleasant, and the landscapes are at their verdant best.",
    weather: "Tropical climate, monsoon from June to August",
    best_time_of_visit: "September to February",
    image: "https://www.holidify.com/images/bgImages/KERALA.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b35dbd1e430a108f0a89",
    name: "Varanasi",
    state: "Uttar Pradesh",
    city: "Varanasi",
    info: "World's oldest living city, Varanasi - also known as Kashi (City of Life) and Benaras, is the spiritual capital of India. \n It is one of Hinduism's seven holy cities. The old city of Varanasi lies along the western banks of the Ganges, spread across a labyrinth of narrow galis.  Be prepared to walk on foot and encounter some holy cows! Temples at almost every turn engulf Varanasi but the Kashi Vishwanath Temple is the most visited and the oldest of the lot. Benaras is known as the city of Lord Shiva for a reason, and rightfully so.\n Varanasi is considered an auspicious place to die, as it is believed to grant moksha or liberation from the cycle of life and death. One of the city's most iconic features are the 80 ghats along the Ganges, where daily life unfolds against the backdrop of rituals, ceremonies, and spiritual practices. Dashashwamedh Ghat, the main ghat, witnesses the mesmerizing Ganga Aarti, a captivating ritual where priests offer prayers to the river with the rhythmic movement of lamps, fire, and chants. The boat ride along the Ganges during sunrise or sunset provides a serene and immersive experience, allowing visitors to witness the city's timeless beauty.\n The narrow winding lanes of Varanasi, known as galis, house numerous shrines, shops, and eateries, creating a maze that leads to hidden gems like the historic Sarnath, where Lord Buddha gave his first sermon. The city is a kaleidoscope of colors and sounds during festivals, especially during Diwali and Holi. The vibrant ghats, adorned with thousands of diyas (lamps) during Diwali, create a mesmerizing spectacle. Varanasi's local markets, such as the Vishwanath Gali and Thatheri Bazaar, offer an array of handcrafted silk, brassware, and traditional Banarasi sarees.\n The best time to visit Varanasi is during the winter months (October to March), when the weather is pleasant, and the city is vibrant with festivals and cultural events.",
    weather: "Hot summers, cool winters (October to March)",
    best_time_of_visit: "October - March",
    image: "https://www.holidify.com/images/bgImages/VARANASI.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b368bd1e430a108f0a8b",
    name: "Mumbai",
    state: "Maharashtra",
    city: "Mumbai",
    info: "Mumbai, the capital city of the Indian state of Maharashtra, is a spectacular paradox of chaos and hope, glamour and squalor, modernity and tradition. Famously known as the City of Dreams, \n Mumbai – formerly known as Bombay - Mumbai is a beautifully blended melting pot of cultures and lifestyles.\n The city soaks in everything into its fabric, making it its very own. From upcoming actors struggling to make it big on the silver screen; from Bolly superstars to big industrialists to tribes of fisherman and slum dwellers, Mumbai is a city that proudly boasts of stories from different walks of human survival.\n One of the main centres in the country of art, culture, music, dance and theatre, Mumbai is a dynamic, cosmopolitan city that has been running for years solely on the indomitable spirit of the Mumbaikars.",
    weather: "Humid (June to September), moderate (October to March)",
    best_time_of_visit: "November to February",
    image: "https://www.holidify.com/images/bgImages/MUMBAI.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b3d7bd1e430a108f0a8d",
    name: "Rishikesh",
    state: "Uttarakhand",
    city: "Rishikesh",
    info: "Located in the foothills of the Himalayas along the convergence of Ganga and Chandrabhaga River, Rishikesh is a small town in the Dehradun district, located close to Haridwar in Uttarakhand. \n Rishikesh (also called as Hrishikesh) is known for its adventure activities, ancient temples, popular cafes and as the 'Yoga Capital of the World'. Gateway to Garhwal Himalayas, Rishikesh is also a pilgrimage town and one of the holiest places for Hindus.\n Rishikesh became known worldwide in the 1960s after The Beatles visited the ashram of Maharishi Mahesh Yogi here. Today, the place is popular as The Beatles Ashram which beckons tourists globally. The tranquil town has long been a spiritual centre but is equally popular for the whitewater rafting, bungee jumping, mountain biking and camping along the fast-flowing Holy Ganges. It also serves as the gateway to many Himalayan treks. As it lies on the holy banks of river Ganga, Rishikesh has been a hub of Sadhus (saints) with numerous ashrams teaching spirituality, yoga, meditation and Ayurveda springing up. Since it is a religious town, non-vegetarian food and alcohol are strictly prohibited here. Rishikesh sees the most beautiful evening aarti on the banks of the river Ganga, which is not too crowded unlike its contemporaries in Varanasi, and Haridwar. The International Yoga Festival is organised here in the first week of March which sees yoga enthusiasts from all over the globe.\n Rishikesh is divided into two main areas - the downtown area known as Rishikesh town which is where the popular Triveni Ghat is situated. 2 km upstream from the popular Ram Jhula and Lakshman Jhula is the other side of Rishikesh where most of the popular ashrams, cafes, accommodation and tourists can be found. Haridwar and Rishikesh are the first Indian cities to be given the title of 'twin national heritage cities",
    weather: "Moderate climate, hot in summers, cool in winters",
    best_time_of_visit: "September to April",
    image: "https://www.holidify.com/images/bgImages/RISHIKESH.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b3e4bd1e430a108f0a8f",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    city: "Khajuraho",
    info: "Khajuraho, a UNESCO World Heritage Site located in Madhya Pradesh, is known around the world for its stunning temples adorned by erotic and sensuous carvings. A small town located in the Bundelkhand region, \n Khajuraho is a brilliant example of Indian architecture and its culture back in the medieval period. The architecture of these Hindu and Jain temples depict the erotic forms of love, the carvings on the walls display passion in the most sensuous yet aesthetic ways. Built between 950 to 1050 AD the sheer confrontational nature of these carvings shows a stark paradox with the conventional Indian ideals about eroticism, leaving everybody spellbound.\n Art in this small town is engrained in all of its structures and are a classic example of the finesse of India's cultural and artistic heritage. The best part about Khajuraho is that although scores of plunderers tried to destroy the whole complex, they could never succeed, even though they managed to reduce the number of temples and caves to 25 from a staggering 85 at the time it was created.",
    weather: "Hot summers, cool winters (October to March)",
    best_time_of_visit: "October to March",
    image: "https://www.holidify.com/images/bgImages/KHAJURAHO.jpg",
    reviews: [],
    __v: 0,
  },
  {
    _id: "65d7b3f0bd1e430a108f0a91",
    name: "Andaman and Nicobar Islands",
    state: "Andaman and Nicobar Islands",
    city: "Port Blair",
    info: "Replete with turquoise blue water beaches and a bit of history, Andaman & Nicobar Islands is a little slice of paradise tucked around 1,400 km away from the east coast of mainland India.\n  Port Blair, the capital of this union territory, has a major airport and seaport connected with the rest of the country and with various tourist islands via multiple daily ferries. Havelock and Neil Islands are popular among tourists for their white sandy beaches and excellent diving options. \n Andaman & Nicobar Islands comprises 572 islands, only 37 of which are inhabited, and a few are open to tourists. Havelock Island is one of the largest and the most popular islands of all Andaman & Nicobar Islands. Travellers typically enter from Port Blair via flight or ship and spend multiple nights in Havelock and Neil Islands that offer some great resorts.\n The southern coast of the Havelock island has the charming Radhanagar Beach, while the azure beauty of Vijayanagar Beach is situated towards the east of the island.  Perhaps the most endearing feature of Neil island is its three sandy beaches, namely Bharatpur Beach, Sitapur Beach and Lakshmanpur Beaches.\n Port Blair is generally used as a base city to catch ferries to nearby islands. However, tourists also spend a day or two here to explore the town and nearby beaches. People also take day trips to Ross Island and North Bay Island or Baratang and Jolly Buoy island from Port Blair.\n Andamans have the most exotic beach and some of them also give the opportunity of trying out a number of Water sports such as Scuba Diving, Snorkeling, Sea Walk etc. North Bay Island near Port Blair, Elephant Beach in Havelock Island and Bharatpur Beach in Neil Island are three popular beaches to try out watersports. Elephant beach and Kalapather beach are two other beaches where the sunrise and sunsets are absolutely divine.",
    weather: "Tropical climate, monsoon from May to September",
    best_time_of_visit: "November to April",
    image: "https://www.holidify.com/images/bgImages/ANDAMAN.jpg",
    reviews: [],
    __v: 0,
  },
];
export { places };
